# Generated by Django 3.1.2 on 2020-12-10 01:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('rutEmpresa', models.CharField(help_text='Sin puntos, con guion', max_length=10, primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=50)),
                ('direccionEmpresa', models.CharField(max_length=50)),
                ('telefonoEmpresa', models.CharField(max_length=9)),
                ('correoEmpresa', models.EmailField(max_length=50)),
                ('ciudadEmpresa', models.CharField(max_length=50)),
                ('comunaEmpresa', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
                ('nombreRepresentante', models.CharField(max_length=50)),
                ('rutRepresentante', models.CharField(help_text='Sin puntos, con guion', max_length=10)),
                ('contraseñaEmpresa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRepartidor',
            fields=[
                ('rutRepartidor', models.CharField(help_text='Sin puntos, con guion', max_length=10, primary_key=True, serialize=False)),
                ('nombreRepartidor', models.CharField(max_length=50)),
                ('apellidosRepartidor', models.CharField(max_length=50)),
                ('direccionRepartidor', models.CharField(max_length=50)),
                ('telefonoRepartidor', models.CharField(max_length=9)),
                ('correoRepartidor', models.EmailField(max_length=50)),
                ('ciudadRepartidor', models.CharField(max_length=50)),
                ('comunaRepartidor', models.CharField(max_length=50)),
                ('contraseñaRepartidor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('usuarioR', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telollevo.usuariorepartidor')),
            ],
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('direccionDestino', models.CharField(max_length=50)),
                ('nombreDestino', models.CharField(max_length=50)),
                ('rutDestino', models.CharField(help_text='Sin puntos, con guion', max_length=10)),
                ('telefonoDestino', models.CharField(max_length=9)),
                ('correoDestino', models.EmailField(max_length=50)),
                ('fechaEnvio', models.DateField()),
                ('fechaEstimadaEntrega', models.DateField()),
                ('estadoEnvio', models.CharField(blank=True, choices=[('d', 'Despachado'), ('t', 'En Transito'), ('e', 'Entregado'), ('w', 'En Espera'), ('n', 'No se encuentra en domicilio')], default='w', help_text='Estado del Envío', max_length=1)),
                ('usuarioE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telollevo.usuarioempresa')),
                ('usuarioR', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telollevo.usuariorepartidor')),
            ],
        ),
    ]
